export const INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export const LOGIN_USER = 'App/LOGIN_USER';
export const LOGOUT_USER = 'App/LOGOUT_USER';
